### ISSUE TITLE
Increase the duration to show the submission feedback message

### ISSUE THREAD

**Issue by julienrf** [scalacenter/cfp-app#16]

**Comment by darjutak** [comment]
Quoting René: "Isn't there a possibility to let the reader close the window as he sees fit? Or integrate the text into the page itself and let it stand there?"

**Comment by julienrf** [comment]
Yeah, actually that’s what I’ve done in #21 (the pop-up never auto-closes)

**Comment by darjutak** [comment]
awesome !
